Adding necessary travis and hound dotfiles
fschueller/crowbar-nagios pull request #2
Opened 2016-09-14 15:48 UTC by fschueller

2016-09-15 09:44 UTC, rsalevsky commented
Can you delete the .lgtm config? I think we don't need it here.

2016-09-16 09:29 UTC, dirkmueller requested changes
remove the ~/.lgtm, rest looks good

2016-11-03 10:42 UTC, toabctl approved these changes

2016-11-03 10:46 UTC, aplanas approved these changes

2016-11-03 23:06 UTC, merged